# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-17 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=8)),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('phone', models.CharField(max_length=11)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
