# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-22 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myplakaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='name',
        ),
        migrations.RemoveField(
            model_name='search',
            name='surname',
        ),
        migrations.AddField(
            model_name='search',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='search',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
